name: EZRep Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.7
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore SideWarsServer.sln

    - name: Build Solution
      run: |
        msbuild.exe SideWarsServer.sln /p:OutDir="../_build" /p:configuration="Release" /t:restore,build
        
    - name: Test Solution
      run: |
        dotnet test ./_build/SideWarsServerTests.dll
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SideWarsServer
        path: "./_build"      
